language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
      - sudo apt-get update
      - sudo apt-get build-dep python-tables

      # We do this conditionally because it saves us some downloading if the
      # version is the same.
      - wget https://repo.continuum.io/archive/Anaconda3-4.3.1-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda

      # Useful for debugging any issues with conda
      - conda info -a

      # Replace dep1 dep2 ... with your dependencies
      - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION anaconda
      - source activate test-environment

      - pip install tables
      - python setup.py install

# command to run tests
script:
 - source activate test-environment
 - python setup.py test