language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
      - sudo apt-get update
      - sudo apt-get build-dep python-tables
      - sudo apt-get install libblas-dev liblapack-dev

      # We do this conditionally because it saves us some downloading if the
      # version is the same.
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda update --all
      - conda upgrade --all

      # Useful for debugging any issues with conda
      - conda info -a

      # Replace dep1 dep2 ... with your dependencies
      - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION anaconda numpy scipy pandas statsmodels matplotlib numexpr pytables
      - source activate test-environment
      - python setup.py install
      - pip install coverage

# command to run tests
script:
 - source activate test-environment
 - coverage run --source=enrich2/base/,enrich2/config/,enrich2/experiment/,enrich2/libraries/,enrich2/selection/,enrich2/sequence/,enrich2/statistics/ setup.py test
 - coverage report