language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "pypy3"
      env: NO_MYPY=true
  allow_failures:
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "pypy3"
      env: NO_MYPY=true
install:
  - pip3 install .
before_script:
  - pip3 install coverage
  - pip3 install coveralls
  - if ! $NO_MYPY; then pip3 install mypy; fi
script:
  - coverage run --source enrich2 -m unittest discover -s tests
  - if ! $NO_MYPY; then mypy enrich2 tests; fi
after_success:
  - coveralls