language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
    - "pip install tables"
    - "python setup.py install"

# command to run tests
script: "python setup.py test"