language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install: "python setup.py install --user"

# command to run tests
script: "python setup.py test"